# Generated by Django 5.2.3 on 2025-06-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_cliente",
                    models.CharField(max_length=50, verbose_name="Nombre Cliente"),
                ),
                (
                    "celular",
                    models.CharField(max_length=80, verbose_name="Número Celular"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=50, verbose_name="Descripción"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Precio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "Productos",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "rut",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="RUT del Proveedor",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=50, verbose_name="Razón Social"),
                ),
                ("telefono", models.CharField(max_length=80, verbose_name="Teléfono")),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "Proveedor",
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "num",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Número de Factura",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de Factura")),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Importe Total"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="ID_Cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_empresa.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "db_table": "Factura",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del Pedido")),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="ID_Cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_empresa.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        db_column="Codigo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_empresa.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": "Pedidos",
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="id_proveedor",
            field=models.ForeignKey(
                db_column="ID_Proveedor",
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_empresa.proveedor",
                verbose_name="Proveedor",
            ),
        ),
        migrations.CreateModel(
            name="FacturaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        db_column="Num_Factura",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_empresa.factura",
                        verbose_name="Número de Factura",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        db_column="Codigo_Producto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_empresa.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Factura",
                "verbose_name_plural": "Detalles de Factura",
                "db_table": "Factura_Detalle",
                "unique_together": {("factura", "producto")},
            },
        ),
    ]
