# Generated by Django 5.2.3 on 2025-06-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_empresa", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="nombre_cliente",
            new_name="NombreCliente",
        ),
    ]
