# Generated by Django 5.2.3 on 2025-06-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_empresa", "0002_rename_nombre_cliente_cliente_nombrecliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturadetalle",
            name="producto",
            field=models.ForeignKey(
                db_column="Codigo_Producto",
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_empresa.producto",
                verbose_name="Productos",
            ),
        ),
        migrations.AlterModelTable(
            name="proveedor",
            table="Proveedores",
        ),
    ]
