# Generated by Django 5.2.3 on 2025-07-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_empresa", "0003_alter_facturadetalle_producto_alter_proveedor_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="id",
        ),
        migrations.AddField(
            model_name="producto",
            name="codigo",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
