# Generated by Django 5.2.3 on 2025-07-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_empresa", "0004_remove_producto_id_producto_codigo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="id",
        ),
        migrations.AddField(
            model_name="pedido",
            name="id_pedido",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID del Pedido"
            ),
        ),
    ]
